//// Standardize to hit and damage bonus from enchantment on launchers and ammo

COPY_EXISTING_REGEXP GLOB ~.*\.itm$~ ~override~
	READ_SHORT 0x1c item_type
	PATCH_IF (%SOURCE_SIZE% > 0x7f) AND (item_type = 0x0f) BEGIN
		GET_OFFSET_ARRAY global ITM_V10_GEN_EFFECTS
		PHP_EACH global AS ind => res BEGIN
			PATCH_IF (SHORT_AT res)=1 BEGIN // ApR modifier
				WRITE_LONG res+0x4 THIS>=6 ? (THIS - 5) : (THIS>=1 && THIS<=4) ? (THIS + 6) : THIS
			END
		END
	END
BUT_ONLY
